// Verilator C++ testbench for display module
// This is a C++ wrapper that drives the Verilog module generated by Verilator

#include <verilated.h>
#include <verilated_vcd_c.h>
#include "Vdisplay.h"
#include <iostream>
#include <cstdlib>

vluint64_t main_time = 0;  // Current simulation time

double sc_time_stamp() {
    return main_time;
}

int main(int argc, char** argv) {
    // Initialize Verilator
    Verilated::commandArgs(argc, argv);
    Verilated::traceEverOn(true);
    
    // Create instance of the module
    Vdisplay* top = new Vdisplay;
    
    // Create VCD trace file
    VerilatedVcdC* tfp = new VerilatedVcdC;
    top->trace(tfp, 99);
    tfp->open("display_tb.vcd");
    
    // Initialize inputs
    top->clk_74a = 0;
    top->clk_74b = 0;
    top->clk_core_12288 = 0;
    top->clk_core_12288_90deg = 0;
    top->reset_n = 0;
    top->cont1_key = 0;
    top->bridge_addr = 0;
    top->bridge_wr = 0;
    top->bridge_wr_data = 0;
    
    // Clock periods (in simulation time units)
    const vluint64_t CLK_74_PERIOD = 2;      // ~13.5ns period for 74MHz
    const vluint64_t CLK_12288_PERIOD = 1;   // ~81ns period for 12.288MHz
    
    // Simulation parameters
    const vluint64_t SIM_TIME = 100000;      // Total simulation time
    const vluint64_t RESET_TIME = 100;       // Reset duration
    
    std::cout << "Starting display module simulation..." << std::endl;
    
    // Main simulation loop
    while (main_time < SIM_TIME && !Verilated::gotFinish()) {
        // Toggle clocks
        if (main_time % CLK_74_PERIOD == 0) {
            top->clk_74a = !top->clk_74a;
            top->clk_74b = top->clk_74a;  // Same frequency, can be phase-shifted if needed
        }
        
        if (main_time % CLK_12288_PERIOD == 0) {
            top->clk_core_12288 = !top->clk_core_12288;
            // 90 degree phase shift: delay by 1/4 period
            top->clk_core_12288_90deg = (main_time % (CLK_12288_PERIOD * 4)) < (CLK_12288_PERIOD * 2);
        }
        
        // Release reset
        if (main_time == RESET_TIME) {
            top->reset_n = 1;
            std::cout << "Reset released at time " << main_time << std::endl;
        }
        
        // Test stimulus: write to bridge
        if (main_time == 1000) {
            top->bridge_addr = 0x00F0000C;
            top->bridge_wr_data = 0x7;  // Enable all channels
            top->bridge_wr = 1;
            std::cout << "Writing to bridge at time " << main_time << std::endl;
        } else if (main_time == 1002) {
            top->bridge_wr = 0;
        }
        
        // Toggle controller key
        if (main_time == 5000) {
            top->cont1_key = 0x10;  // Set face_a button
            std::cout << "Controller key pressed at time " << main_time << std::endl;
        }
        
        // Evaluate model
        top->eval();
        
        // Dump trace
        tfp->dump(main_time);
        
        // Increment simulation time
        main_time++;
    }
    
    // Final evaluation
    top->final();
    
    // Close trace file
    tfp->close();
    
    // Cleanup
    delete top;
    delete tfp;
    
    std::cout << "Simulation completed. Trace saved to display_tb.vcd" << std::endl;
    
    return 0;
}
